export const DEFAULT_CATEGORIES = [
  { name: 'Food & Dining', type: 'EXPENSE', icon: 'utensils', color: '#10b981' },
  { name: 'Groceries', type: 'EXPENSE', icon: 'shopping-cart', color: '#06b6d4' },
  { name: 'Transportation', type: 'EXPENSE', icon: 'car', color: '#3b82f6' },
  { name: 'Housing & Rent', type: 'EXPENSE', icon: 'home', color: '#8b5cf6' },
  { name: 'Utilities', type: 'EXPENSE', icon: 'zap', color: '#f59e0b' },
  { name: 'Shopping', type: 'EXPENSE', icon: 'bag', color: '#ec4899' },
  { name: 'Entertainment', type: 'EXPENSE', icon: 'film', color: '#f43f5e' },
  { name: 'Healthcare', type: 'EXPENSE', icon: 'activity', color: '#14b8a6' },
  { name: 'Education', type: 'EXPENSE', icon: 'book', color: '#6366f1' },
  { name: 'Travel', type: 'EXPENSE', icon: 'plane', color: '#0ea5e9' },
  { name: 'Personal Care', type: 'EXPENSE', icon: 'smile', color: '#d946ef' },
  { name: 'Salary', type: 'INCOME', icon: 'briefcase', color: '#10b981' },
  { name: 'Freelance', type: 'INCOME', icon: 'code', color: '#3b82f6' },
  { name: 'Investments', type: 'INCOME', icon: 'trending-up', color: '#8b5cf6' },
  { name: 'Gifts & Grants', type: 'INCOME', icon: 'gift', color: '#f59e0b' },
  { name: 'Other Income', type: 'INCOME', icon: 'plus-circle', color: '#14b8a6' },
  { name: 'Other Expense', type: 'EXPENSE', icon: 'minus-circle', color: '#64748b' },
];
